/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { a, SpringValue, useSpring } from '@react-spring/three'

type GLTFResult = GLTF & {
  nodes: {
    mesh0_meshnode_0: THREE.Mesh
    mesh1_meshnode_1: THREE.Mesh
    mesh2_meshnode_2: THREE.Mesh
    mesh3_meshnode_3: THREE.Mesh
    mesh4_meshnode_4: THREE.Mesh
    mesh5_meshnode_5: THREE.Mesh
    mesh6_meshnode_6: THREE.Mesh
    mesh7_meshnode_7: THREE.Mesh
    mesh8_meshnode_8: THREE.Mesh
    mesh9_meshnode_9: THREE.Mesh
    mesh0_meshnode_0_1: THREE.Mesh
    mesh1_meshnode_1_1: THREE.Mesh
    mesh2_meshnode_2_1: THREE.Mesh
    mesh3_meshnode_3_1: THREE.Mesh
    mesh4_meshnode_4_1: THREE.Mesh
    mesh5_meshnode_5_1: THREE.Mesh
    mesh6_meshnode_6_1: THREE.Mesh
    mesh7_meshnode_7_1: THREE.Mesh
    mesh8_meshnode_8_1: THREE.Mesh
    mesh9_meshnode_9_1: THREE.Mesh
    mesh10_meshnode_10: THREE.Mesh
    mesh11_meshnode_11: THREE.Mesh
    mesh12_meshnode_12: THREE.Mesh
    mesh13_meshnode_13: THREE.Mesh
    mesh0_meshnode_0_2: THREE.Mesh
    mesh1_meshnode_1_2: THREE.Mesh
    mesh2_meshnode_2_2: THREE.Mesh
    mesh3_meshnode_3_2: THREE.Mesh
    mesh4_meshnode_4_2: THREE.Mesh
    mesh5_meshnode_5_2: THREE.Mesh
    mesh6_meshnode_6_2: THREE.Mesh
    mesh7_meshnode_7_2: THREE.Mesh
    mesh8_meshnode_8_2: THREE.Mesh
    mesh9_meshnode_9_2: THREE.Mesh
    mesh10_meshnode_10_1: THREE.Mesh
    mesh11_meshnode_11_1: THREE.Mesh
    mesh12_meshnode_12_1: THREE.Mesh
    mesh13_meshnode_13_1: THREE.Mesh
    mesh0_meshnode_0_3: THREE.Mesh
    mesh1_meshnode_1_3: THREE.Mesh
    mesh2_meshnode_2_3: THREE.Mesh
    mesh3_meshnode_3_3: THREE.Mesh
    mesh4_meshnode_4_3: THREE.Mesh
    mesh5_meshnode_5_3: THREE.Mesh
    mesh6_meshnode_6_3: THREE.Mesh
    mesh7_meshnode_7_3: THREE.Mesh
    mesh8_meshnode_8_3: THREE.Mesh
    mesh9_meshnode_9_3: THREE.Mesh
    mesh10_meshnode_10_2: THREE.Mesh
    mesh11_meshnode_11_2: THREE.Mesh
    mesh12_meshnode_12_2: THREE.Mesh
    mesh13_meshnode_13_2: THREE.Mesh
    mesh14_meshnode_14: THREE.Mesh
    mesh15_meshnode_15: THREE.Mesh
    mesh16_meshnode_16: THREE.Mesh
    mesh17_meshnode_17: THREE.Mesh
    mesh18_meshnode_18: THREE.Mesh
    mesh19_meshnode_19: THREE.Mesh
    mesh20_meshnode_20: THREE.Mesh
    mesh21_meshnode_21: THREE.Mesh
    mesh22_meshnode_22: THREE.Mesh
    mesh23_meshnode_23: THREE.Mesh
    mesh24_meshnode_24: THREE.Mesh
    mesh25_meshnode_25: THREE.Mesh
    mesh26_meshnode_26: THREE.Mesh
    mesh27_meshnode_27: THREE.Mesh
    mesh28_meshnode_28: THREE.Mesh
    mesh29_meshnode_29: THREE.Mesh
    mesh30_meshnode_30: THREE.Mesh
    mesh31_meshnode_31: THREE.Mesh
    mesh32_meshnode_32: THREE.Mesh
    mesh33_meshnode_33: THREE.Mesh
    mesh0_meshnode_0_4: THREE.Mesh
    mesh1_meshnode_1_4: THREE.Mesh
    mesh2_meshnode_2_4: THREE.Mesh
    mesh3_meshnode_3_4: THREE.Mesh
    mesh4_meshnode_4_4: THREE.Mesh
    mesh5_meshnode_5_4: THREE.Mesh
    mesh6_meshnode_6_4: THREE.Mesh
    mesh7_meshnode_7_4: THREE.Mesh
    mesh8_meshnode_8_4: THREE.Mesh
    mesh9_meshnode_9_4: THREE.Mesh
    mesh10_meshnode_10_3: THREE.Mesh
    mesh11_meshnode_11_3: THREE.Mesh
    mesh12_meshnode_12_3: THREE.Mesh
    mesh13_meshnode_13_3: THREE.Mesh
    mesh14_meshnode_14_1: THREE.Mesh
    mesh15_meshnode_15_1: THREE.Mesh
    mesh16_meshnode_16_1: THREE.Mesh
    mesh17_meshnode_17_1: THREE.Mesh
    mesh18_meshnode_18_1: THREE.Mesh
    mesh19_meshnode_19_1: THREE.Mesh
    mesh20_meshnode_20_1: THREE.Mesh
    mesh21_meshnode_21_1: THREE.Mesh
    mesh22_meshnode_22_1: THREE.Mesh
    mesh23_meshnode_23_1: THREE.Mesh
    mesh24_meshnode_24_1: THREE.Mesh
    mesh25_meshnode_25_1: THREE.Mesh
    mesh26_meshnode_26_1: THREE.Mesh
    mesh27_meshnode_27_1: THREE.Mesh
    mesh0_meshnode_0_5: THREE.Mesh
    mesh1_meshnode_1_5: THREE.Mesh
    mesh2_meshnode_2_5: THREE.Mesh
    mesh3_meshnode_3_5: THREE.Mesh
    mesh4_meshnode_4_5: THREE.Mesh
    mesh5_meshnode_5_5: THREE.Mesh
    mesh6_meshnode_6_5: THREE.Mesh
    mesh7_meshnode_7_5: THREE.Mesh
    mesh8_meshnode_8_5: THREE.Mesh
    mesh9_meshnode_9_5: THREE.Mesh
    mesh10_meshnode_10_4: THREE.Mesh
    mesh11_meshnode_11_4: THREE.Mesh
    mesh12_meshnode_12_4: THREE.Mesh
    mesh13_meshnode_13_4: THREE.Mesh
    mesh14_meshnode_14_2: THREE.Mesh
    mesh15_meshnode_15_2: THREE.Mesh
    mesh16_meshnode_16_2: THREE.Mesh
    mesh17_meshnode_17_2: THREE.Mesh
    mesh18_meshnode_18_2: THREE.Mesh
    mesh19_meshnode_19_2: THREE.Mesh
    mesh20_meshnode_20_2: THREE.Mesh
    mesh21_meshnode_21_2: THREE.Mesh
    mesh22_meshnode_22_2: THREE.Mesh
    mesh23_meshnode_23_2: THREE.Mesh
    mesh24_meshnode_24_2: THREE.Mesh
    mesh25_meshnode_25_2: THREE.Mesh
    mesh26_meshnode_26_2: THREE.Mesh
    mesh27_meshnode_27_2: THREE.Mesh
    Mid_2_Camara_material_0: THREE.Mesh
    cilindro_low1_lambert3_0: THREE.Mesh
    cilindro_low1_lambert4_0: THREE.Mesh
    cilindro_low1_lambert1_0: THREE.Mesh
    cilindro_low1_Cilindro_material_0: THREE.Mesh
    pCylinder9_ruleta__0: THREE.Mesh
    pCylinder8_ruleta_2_0: THREE.Mesh
  }
  materials: {
    ['0.070588_0.070588_0.070588_0.000000_0.000000']: THREE.MeshStandardMaterial
    ['0.070588_0.070588_0.070588_0.000000_0.000000']: THREE.MeshStandardMaterial
    ['0.070588_0.070588_0.070588_0.000000_0.000000']: THREE.MeshStandardMaterial
    ['0.125490_0.125490_0.125490_0.000000_0.000000']: THREE.MeshStandardMaterial
    ['0.125490_0.125490_0.125490_0.000000_0.000000']: THREE.MeshStandardMaterial
    ['0.125490_0.125490_0.125490_0.000000_0.000000']: THREE.MeshStandardMaterial
    Camara_material: THREE.MeshStandardMaterial
    lambert3: THREE.MeshPhysicalMaterial
    lambert4: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    Cilindro_material: THREE.MeshStandardMaterial
    ruleta: THREE.MeshStandardMaterial
    ruleta_2: THREE.MeshStandardMaterial
  }
}


export default function Scene(props: JSX.IntrinsicElements['group']&{yaw:number,pitch:number}) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/scene.glb') as GLTFResult
  const [{ x }] = useSpring({ x: props.yaw, config: { mass: 5, tension: 1000, friction: 50, precision: 0.0001 } }, [props.yaw])
	const [{ y }] = useSpring({ y: props.pitch, config: { mass: 5, tension: 1000, friction: 50, precision: 0.0001 } }, [props.pitch])
  return (
    <group ref={group} {...props} dispose={null}>
      <a.group scale={1} rotation={[0,0,0]}>
        <a.group rotation={[-Math.PI / 2, 0, 0]}>
          <a.mesh geometry={nodes.mesh0_meshnode_0.geometry} material={nodes.mesh0_meshnode_0.material} />
          <a.mesh geometry={nodes.mesh1_meshnode_1.geometry} material={nodes.mesh1_meshnode_1.material} />
          <a.mesh geometry={nodes.mesh2_meshnode_2.geometry} material={nodes.mesh2_meshnode_2.material} />
          <a.mesh geometry={nodes.mesh3_meshnode_3.geometry} material={nodes.mesh3_meshnode_3.material} />
          <a.mesh geometry={nodes.mesh4_meshnode_4.geometry} material={nodes.mesh4_meshnode_4.material} />
          <a.mesh geometry={nodes.mesh5_meshnode_5.geometry} material={nodes.mesh5_meshnode_5.material} />
          <a.mesh geometry={nodes.mesh6_meshnode_6.geometry} material={nodes.mesh6_meshnode_6.material} />
          <a.mesh geometry={nodes.mesh7_meshnode_7.geometry} material={nodes.mesh7_meshnode_7.material} />
          <a.mesh geometry={nodes.mesh8_meshnode_8.geometry} material={nodes.mesh8_meshnode_8.material} />
          <a.mesh geometry={nodes.mesh9_meshnode_9.geometry} material={nodes.mesh9_meshnode_9.material} />
        </a.group>
        <a.group rotation={[-Math.PI / 2, 0, 0]}>
          <a.mesh geometry={nodes.mesh0_meshnode_0_1.geometry} material={nodes.mesh0_meshnode_0_1.material} />
          <a.mesh geometry={nodes.mesh1_meshnode_1_1.geometry} material={nodes.mesh1_meshnode_1_1.material} />
          <a.mesh geometry={nodes.mesh2_meshnode_2_1.geometry} material={nodes.mesh2_meshnode_2_1.material} />
          <a.mesh geometry={nodes.mesh3_meshnode_3_1.geometry} material={nodes.mesh3_meshnode_3_1.material} />
          <a.mesh geometry={nodes.mesh4_meshnode_4_1.geometry} material={nodes.mesh4_meshnode_4_1.material} />
          <a.mesh geometry={nodes.mesh5_meshnode_5_1.geometry} material={nodes.mesh5_meshnode_5_1.material} />
          <a.mesh geometry={nodes.mesh6_meshnode_6_1.geometry} material={nodes.mesh6_meshnode_6_1.material} />
          <a.mesh geometry={nodes.mesh7_meshnode_7_1.geometry} material={nodes.mesh7_meshnode_7_1.material} />
          <a.mesh geometry={nodes.mesh8_meshnode_8_1.geometry} material={nodes.mesh8_meshnode_8_1.material} />
          <a.mesh geometry={nodes.mesh9_meshnode_9_1.geometry} material={nodes.mesh9_meshnode_9_1.material} />
          <a.mesh geometry={nodes.mesh10_meshnode_10.geometry} material={nodes.mesh10_meshnode_10.material} />
          <a.mesh geometry={nodes.mesh11_meshnode_11.geometry} material={nodes.mesh11_meshnode_11.material} />
          <a.mesh geometry={nodes.mesh12_meshnode_12.geometry} material={nodes.mesh12_meshnode_12.material} />
          <a.mesh geometry={nodes.mesh13_meshnode_13.geometry} material={nodes.mesh13_meshnode_13.material} />
        </a.group>
        <a.group rotation={[-Math.PI / 2, 0, Math.PI]}>
          <a.mesh geometry={nodes.mesh0_meshnode_0_2.geometry} material={nodes.mesh0_meshnode_0_2.material} />
          <a.mesh geometry={nodes.mesh1_meshnode_1_2.geometry} material={nodes.mesh1_meshnode_1_2.material} />
          <a.mesh geometry={nodes.mesh2_meshnode_2_2.geometry} material={nodes.mesh2_meshnode_2_2.material} />
          <a.mesh geometry={nodes.mesh3_meshnode_3_2.geometry} material={nodes.mesh3_meshnode_3_2.material} />
          <a.mesh geometry={nodes.mesh4_meshnode_4_2.geometry} material={nodes.mesh4_meshnode_4_2.material} />
          <a.mesh geometry={nodes.mesh5_meshnode_5_2.geometry} material={nodes.mesh5_meshnode_5_2.material} />
          <a.mesh geometry={nodes.mesh6_meshnode_6_2.geometry} material={nodes.mesh6_meshnode_6_2.material} />
          <a.mesh geometry={nodes.mesh7_meshnode_7_2.geometry} material={nodes.mesh7_meshnode_7_2.material} />
          <a.mesh geometry={nodes.mesh8_meshnode_8_2.geometry} material={nodes.mesh8_meshnode_8_2.material} />
          <a.mesh geometry={nodes.mesh9_meshnode_9_2.geometry} material={nodes.mesh9_meshnode_9_2.material} />
          <a.mesh geometry={nodes.mesh10_meshnode_10_1.geometry} material={nodes.mesh10_meshnode_10_1.material} />
          <a.mesh geometry={nodes.mesh11_meshnode_11_1.geometry} material={nodes.mesh11_meshnode_11_1.material} />
          <a.mesh geometry={nodes.mesh12_meshnode_12_1.geometry} material={nodes.mesh12_meshnode_12_1.material} />
          <a.mesh geometry={nodes.mesh13_meshnode_13_1.geometry} material={nodes.mesh13_meshnode_13_1.material} />
        </a.group>
        <a.group position={[0, 0.03, 0]} rotation={[0,0,0]}>
          <a.group position={[0, 0, -0.03]}>
            <a.mesh geometry={nodes.mesh0_meshnode_0_3.geometry} material={nodes.mesh0_meshnode_0_3.material} />
            <a.mesh geometry={nodes.mesh1_meshnode_1_3.geometry} material={nodes.mesh1_meshnode_1_3.material} />
            <a.mesh geometry={nodes.mesh2_meshnode_2_3.geometry} material={nodes.mesh2_meshnode_2_3.material} />
            <a.mesh geometry={nodes.mesh3_meshnode_3_3.geometry} material={nodes.mesh3_meshnode_3_3.material} />
            <a.mesh geometry={nodes.mesh4_meshnode_4_3.geometry} material={nodes.mesh4_meshnode_4_3.material} />
            <a.mesh geometry={nodes.mesh5_meshnode_5_3.geometry} material={nodes.mesh5_meshnode_5_3.material} />
            <a.mesh geometry={nodes.mesh6_meshnode_6_3.geometry} material={nodes.mesh6_meshnode_6_3.material} />
            <a.mesh geometry={nodes.mesh7_meshnode_7_3.geometry} material={nodes.mesh7_meshnode_7_3.material} />
            <a.mesh geometry={nodes.mesh8_meshnode_8_3.geometry} material={nodes.mesh8_meshnode_8_3.material} />
            <a.mesh geometry={nodes.mesh9_meshnode_9_3.geometry} material={nodes.mesh9_meshnode_9_3.material} />
            <a.mesh geometry={nodes.mesh10_meshnode_10_2.geometry} material={nodes.mesh10_meshnode_10_2.material} />
            <a.mesh geometry={nodes.mesh11_meshnode_11_2.geometry} material={nodes.mesh11_meshnode_11_2.material} />
            <a.mesh geometry={nodes.mesh12_meshnode_12_2.geometry} material={nodes.mesh12_meshnode_12_2.material} />
            <a.mesh geometry={nodes.mesh13_meshnode_13_2.geometry} material={nodes.mesh13_meshnode_13_2.material} />
            <a.mesh geometry={nodes.mesh14_meshnode_14.geometry} material={nodes.mesh14_meshnode_14.material} />
            <a.mesh geometry={nodes.mesh15_meshnode_15.geometry} material={nodes.mesh15_meshnode_15.material} />
            <a.mesh geometry={nodes.mesh16_meshnode_16.geometry} material={nodes.mesh16_meshnode_16.material} />
            <a.mesh geometry={nodes.mesh17_meshnode_17.geometry} material={nodes.mesh17_meshnode_17.material} />
            <a.mesh geometry={nodes.mesh18_meshnode_18.geometry} material={nodes.mesh18_meshnode_18.material} />
            <a.mesh geometry={nodes.mesh19_meshnode_19.geometry} material={nodes.mesh19_meshnode_19.material} />
            <a.mesh geometry={nodes.mesh20_meshnode_20.geometry} material={nodes.mesh20_meshnode_20.material} />
            <a.mesh geometry={nodes.mesh21_meshnode_21.geometry} material={nodes.mesh21_meshnode_21.material} />
            <a.mesh geometry={nodes.mesh22_meshnode_22.geometry} material={nodes.mesh22_meshnode_22.material} />
            <a.mesh geometry={nodes.mesh23_meshnode_23.geometry} material={nodes.mesh23_meshnode_23.material} />
            <a.mesh geometry={nodes.mesh24_meshnode_24.geometry} material={nodes.mesh24_meshnode_24.material} />
            <a.mesh geometry={nodes.mesh25_meshnode_25.geometry} material={nodes.mesh25_meshnode_25.material} />
            <a.mesh geometry={nodes.mesh26_meshnode_26.geometry} material={nodes.mesh26_meshnode_26.material} />
            <a.mesh geometry={nodes.mesh27_meshnode_27.geometry} material={nodes.mesh27_meshnode_27.material} />
            <a.mesh geometry={nodes.mesh28_meshnode_28.geometry} material={nodes.mesh28_meshnode_28.material} />
            <a.mesh geometry={nodes.mesh29_meshnode_29.geometry} material={nodes.mesh29_meshnode_29.material} />
            <a.mesh geometry={nodes.mesh30_meshnode_30.geometry} material={nodes.mesh30_meshnode_30.material} />
            <a.mesh geometry={nodes.mesh31_meshnode_31.geometry} material={nodes.mesh31_meshnode_31.material} />
            <a.mesh geometry={nodes.mesh32_meshnode_32.geometry} material={nodes.mesh32_meshnode_32.material} />
            <a.mesh geometry={nodes.mesh33_meshnode_33.geometry} material={nodes.mesh33_meshnode_33.material} />
          </a.group>
          <a.group position={[0, 0, -0.03]} rotation={[0, 0, Math.PI]}>
            <a.mesh geometry={nodes.mesh0_meshnode_0_4.geometry} material={nodes.mesh0_meshnode_0_4.material} />
            <a.mesh geometry={nodes.mesh1_meshnode_1_4.geometry} material={nodes.mesh1_meshnode_1_4.material} />
            <a.mesh geometry={nodes.mesh2_meshnode_2_4.geometry} material={nodes.mesh2_meshnode_2_4.material} />
            <a.mesh geometry={nodes.mesh3_meshnode_3_4.geometry} material={nodes.mesh3_meshnode_3_4.material} />
            <a.mesh geometry={nodes.mesh4_meshnode_4_4.geometry} material={nodes.mesh4_meshnode_4_4.material} />
            <a.mesh geometry={nodes.mesh5_meshnode_5_4.geometry} material={nodes.mesh5_meshnode_5_4.material} />
            <a.mesh geometry={nodes.mesh6_meshnode_6_4.geometry} material={nodes.mesh6_meshnode_6_4.material} />
            <a.mesh geometry={nodes.mesh7_meshnode_7_4.geometry} material={nodes.mesh7_meshnode_7_4.material} />
            <a.mesh geometry={nodes.mesh8_meshnode_8_4.geometry} material={nodes.mesh8_meshnode_8_4.material} />
            <a.mesh geometry={nodes.mesh9_meshnode_9_4.geometry} material={nodes.mesh9_meshnode_9_4.material} />
            <a.mesh geometry={nodes.mesh10_meshnode_10_3.geometry} material={nodes.mesh10_meshnode_10_3.material} />
            <a.mesh geometry={nodes.mesh11_meshnode_11_3.geometry} material={nodes.mesh11_meshnode_11_3.material} />
            <a.mesh geometry={nodes.mesh12_meshnode_12_3.geometry} material={nodes.mesh12_meshnode_12_3.material} />
            <a.mesh geometry={nodes.mesh13_meshnode_13_3.geometry} material={nodes.mesh13_meshnode_13_3.material} />
            <a.mesh geometry={nodes.mesh14_meshnode_14_1.geometry} material={nodes.mesh14_meshnode_14_1.material} />
            <a.mesh geometry={nodes.mesh15_meshnode_15_1.geometry} material={nodes.mesh15_meshnode_15_1.material} />
            <a.mesh geometry={nodes.mesh16_meshnode_16_1.geometry} material={nodes.mesh16_meshnode_16_1.material} />
            <a.mesh geometry={nodes.mesh17_meshnode_17_1.geometry} material={nodes.mesh17_meshnode_17_1.material} />
            <a.mesh geometry={nodes.mesh18_meshnode_18_1.geometry} material={nodes.mesh18_meshnode_18_1.material} />
            <a.mesh geometry={nodes.mesh19_meshnode_19_1.geometry} material={nodes.mesh19_meshnode_19_1.material} />
            <a.mesh geometry={nodes.mesh20_meshnode_20_1.geometry} material={nodes.mesh20_meshnode_20_1.material} />
            <a.mesh geometry={nodes.mesh21_meshnode_21_1.geometry} material={nodes.mesh21_meshnode_21_1.material} />
            <a.mesh geometry={nodes.mesh22_meshnode_22_1.geometry} material={nodes.mesh22_meshnode_22_1.material} />
            <a.mesh geometry={nodes.mesh23_meshnode_23_1.geometry} material={nodes.mesh23_meshnode_23_1.material} />
            <a.mesh geometry={nodes.mesh24_meshnode_24_1.geometry} material={nodes.mesh24_meshnode_24_1.material} />
            <a.mesh geometry={nodes.mesh25_meshnode_25_1.geometry} material={nodes.mesh25_meshnode_25_1.material} />
            <a.mesh geometry={nodes.mesh26_meshnode_26_1.geometry} material={nodes.mesh26_meshnode_26_1.material} />
            <a.mesh geometry={nodes.mesh27_meshnode_27_1.geometry} material={nodes.mesh27_meshnode_27_1.material} />
          </a.group>
          <a.group position={[0, 0, -0.03]}>
            <a.mesh geometry={nodes.mesh0_meshnode_0_5.geometry} material={nodes.mesh0_meshnode_0_5.material} />
            <a.mesh geometry={nodes.mesh1_meshnode_1_5.geometry} material={nodes.mesh1_meshnode_1_5.material} />
            <a.mesh geometry={nodes.mesh2_meshnode_2_5.geometry} material={nodes.mesh2_meshnode_2_5.material} />
            <a.mesh geometry={nodes.mesh3_meshnode_3_5.geometry} material={nodes.mesh3_meshnode_3_5.material} />
            <a.mesh geometry={nodes.mesh4_meshnode_4_5.geometry} material={nodes.mesh4_meshnode_4_5.material} />
            <a.mesh geometry={nodes.mesh5_meshnode_5_5.geometry} material={nodes.mesh5_meshnode_5_5.material} />
            <a.mesh geometry={nodes.mesh6_meshnode_6_5.geometry} material={nodes.mesh6_meshnode_6_5.material} />
            <a.mesh geometry={nodes.mesh7_meshnode_7_5.geometry} material={nodes.mesh7_meshnode_7_5.material} />
            <a.mesh geometry={nodes.mesh8_meshnode_8_5.geometry} material={nodes.mesh8_meshnode_8_5.material} />
            <a.mesh geometry={nodes.mesh9_meshnode_9_5.geometry} material={nodes.mesh9_meshnode_9_5.material} />
            <a.mesh geometry={nodes.mesh10_meshnode_10_4.geometry} material={nodes.mesh10_meshnode_10_4.material} />
            <a.mesh geometry={nodes.mesh11_meshnode_11_4.geometry} material={nodes.mesh11_meshnode_11_4.material} />
            <a.mesh geometry={nodes.mesh12_meshnode_12_4.geometry} material={nodes.mesh12_meshnode_12_4.material} />
            <a.mesh geometry={nodes.mesh13_meshnode_13_4.geometry} material={nodes.mesh13_meshnode_13_4.material} />
            <a.mesh geometry={nodes.mesh14_meshnode_14_2.geometry} material={nodes.mesh14_meshnode_14_2.material} />
            <a.mesh geometry={nodes.mesh15_meshnode_15_2.geometry} material={nodes.mesh15_meshnode_15_2.material} />
            <a.mesh geometry={nodes.mesh16_meshnode_16_2.geometry} material={nodes.mesh16_meshnode_16_2.material} />
            <a.mesh geometry={nodes.mesh17_meshnode_17_2.geometry} material={nodes.mesh17_meshnode_17_2.material} />
            <a.mesh geometry={nodes.mesh18_meshnode_18_2.geometry} material={nodes.mesh18_meshnode_18_2.material} />
            <a.mesh geometry={nodes.mesh19_meshnode_19_2.geometry} material={nodes.mesh19_meshnode_19_2.material} />
            <a.mesh geometry={nodes.mesh20_meshnode_20_2.geometry} material={nodes.mesh20_meshnode_20_2.material} />
            <a.mesh geometry={nodes.mesh21_meshnode_21_2.geometry} material={nodes.mesh21_meshnode_21_2.material} />
            <a.mesh geometry={nodes.mesh22_meshnode_22_2.geometry} material={nodes.mesh22_meshnode_22_2.material} />
            <a.mesh geometry={nodes.mesh23_meshnode_23_2.geometry} material={nodes.mesh23_meshnode_23_2.material} />
            <a.mesh geometry={nodes.mesh24_meshnode_24_2.geometry} material={nodes.mesh24_meshnode_24_2.material} />
            <a.mesh geometry={nodes.mesh25_meshnode_25_2.geometry} material={nodes.mesh25_meshnode_25_2.material} />
            <a.mesh geometry={nodes.mesh26_meshnode_26_2.geometry} material={nodes.mesh26_meshnode_26_2.material} />
            <a.mesh geometry={nodes.mesh27_meshnode_27_2.geometry} material={nodes.mesh27_meshnode_27_2.material} />
          </a.group>
          <a.group position={[0, -0.01, 0.07]} scale={0.02}>
            <a.group rotation={[Math.PI / 2, 0, 0]}>
              <a.group position={[0, 0, -0.69]} scale={[2.02, 1.97, 1.26]}>
                <a.mesh geometry={nodes.Mid_2_Camara_material_0.geometry} material={materials.Camara_material} />
              </a.group>
              <a.group position={[0, 0, -0.01]} scale={0.93}>
                <a.mesh geometry={nodes.cilindro_low1_lambert3_0.geometry} material={materials.lambert3} />
                <a.mesh geometry={nodes.cilindro_low1_lambert4_0.geometry} material={materials.lambert4} />
                <a.mesh geometry={nodes.cilindro_low1_lambert1_0.geometry} material={materials.lambert1} />
                <a.mesh geometry={nodes.cilindro_low1_Cilindro_material_0.geometry} material={materials.Cilindro_material} />
              </a.group>
              <a.group position={[-1.13, 1.08, -0.8]} rotation={[0, 0.02, 0.24]} scale={[0.31, 0.05, 0.31]}>
                <a.mesh geometry={nodes.pCylinder9_ruleta__0.geometry} material={materials.ruleta} />
              </a.group>
              <a.group position={[-1.63, 0.79, 0.09]} rotation={[1.56, 0.01, -0.04]} scale={[0.18, 0.03, 0.18]}>
                <a.mesh geometry={nodes.pCylinder8_ruleta_2_0.geometry} material={materials.ruleta_2} />
              </a.group>
            </a.group>
          </a.group>
        </a.group>
      </a.group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
